### ISSUE TITLE
[BUG] D415 did not work on latest Jetson Xavier NX

### ISSUE THREAD

**Issue by 7oud** [jetsonhacks/installRealSenseSDK#8]
**Describe the issue**
D415 did not work on latest Jetson Xavier NX, [detailed description](https://github.com/IntelRealSense/librealsense/issues/6412)

**What version of L4T/JetPack**
L4T/JetPack version: JetPack 4.4 DP, released on 14 May 2020

**Which Intel RealSense camera(s)**
RealSense camera(s): D415

**Expected behavior**
RealSense Viewer can not work

**Additional context**
I noticed that [installation on jetson from debian](https://github.com/IntelRealSense/librealsense/blob/master/doc/installation_jetson.md) is the same as here. 
if building from source will fix the problem? and may I use the latest librealsense code of master branch to build? or try to use the repo first [buildLibrealsense2Xavier](https://github.com/jetsonhacks/buildLibrealsense2Xavier)

**Comment by AndreV84** [comment]
did not work to what extent? [ using 435i]
I can get it running with realsense-viewer;
used to install librealsense2 with apt-get;
However, I couldn't run
 `rs-hello-realsense 
RealSense error calling rs2_pipeline_wait_for_frames(pipe:0x557f97e110):
    Frame didn't arrive within 15000
`
